import { brief, dashboard, severityIcon, findKpi } from './data';
import { formatValue } from './format';

export function buildMarkdown(): string {
  const lines: string[] = [];
  lines.push(`# RC Operator Signals — ${dashboard.project.name}`);
  lines.push(`> ${dashboard.period.start} → ${dashboard.period.end} (${dashboard.period.days} days)`);
  lines.push('');
  lines.push('## KPI Snapshot');
  for (const kpi of dashboard.kpis) {
    lines.push(`- **${kpi.name}:** ${formatValue(kpi.value, kpi.unit)}`);
  }
  lines.push('');
  lines.push('## Operator Signals');
  for (const signal of [...brief.signals, ...brief.contradictions]) {
    lines.push(`### ${signal.title}`);
    lines.push(signal.detail);
    if (signal.followup) lines.push(`Follow-up: ${signal.followup}`);
    lines.push('');
  }
  lines.push('## Watchlist');
  for (const signal of brief.watchlist) {
    lines.push(`- **${signal.title}** — ${signal.detail}`);
  }
  lines.push('');
  lines.push('## Caveats');
  for (const caveat of brief.caveats) lines.push(`- ${caveat}`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by RC Operator Signals, built by Aurora.*');
  return lines.join('\n');
}

export function buildSlack(): string {
  const topSignals = [...new Map([...brief.signals, ...brief.contradictions].map((s) => [s.id, s])).values()].slice(0, 5);
  return [
    `*RC Operator Signals — ${dashboard.project.name}*`,
    `_${dashboard.period.start} → ${dashboard.period.end}_`,
    '',
    `*MRR* ${formatValue(findKpi('mrr')?.value ?? 0, '$')} · *Revenue* ${formatValue(findKpi('revenue')?.value ?? 0, '$')} · *Subs* ${formatValue(findKpi('active_subscriptions')?.value ?? 0, '#')}`,
    '',
    ...topSignals.map((s) => `${severityIcon[s.severity]} ${s.title}`),
  ].join('\n');
}
