import { useState } from 'react';
import briefData from './data/brief.json';

type Severity = 'info' | 'warning' | 'critical' | 'positive';

interface Signal {
  id: string;
  severity: Severity;
  kind: string;
  title: string;
  detail: string;
  evidence: Array<{ metric: string; value: number; period?: string }>;
  followup?: string;
  caveat?: string;
}

interface Brief {
  generated_at: string;
  project_name: string;
  period: { start: string; end: string };
  snapshot: Array<{
    id: string;
    name: string;
    value: number;
    unit: string;
    period: string;
    description: string;
  }>;
  signals: Signal[];
  contradictions: Signal[];
  watchlist: Signal[];
  caveats: string[];
}

const brief = briefData as unknown as Brief;

function fmt(value: number, unit: string): string {
  if (unit === '$') return `$${value.toLocaleString()}`;
  if (unit === '%') return `${value.toFixed(1)}%`;
  if (value >= 1000) return value.toLocaleString();
  return String(value);
}

function shortPeriod(period: string): string {
  // P28D -> 28d, P0D -> total, etc.
  const m = period.match(/^P(\d+)D$/);
  if (m) return m[1] === '0' ? 'total' : `${m[1]}d`;
  return period;
}

function buildMarkdown(b: Brief): string {
  const lines: string[] = [];
  lines.push(`# Operator Signals — ${b.project_name}`);
  lines.push(`> ${b.period.start} → ${b.period.end} (last 28 days)`);
  lines.push('');
  lines.push('## Snapshot');
  lines.push('| Metric | Value |');
  lines.push('|---|---|');
  for (const m of b.snapshot) lines.push(`| ${m.name} | ${fmt(m.value, m.unit)} |`);
  lines.push('');
  const all = [...b.signals, ...b.contradictions, ...b.watchlist];
  const unique = [...new Map(all.map(s => [s.id, s])).values()];
  if (unique.length > 0) {
    lines.push('## Signals');
    for (const s of unique) {
      lines.push(`### ${s.title}`);
      lines.push(`*${s.severity.toUpperCase()}* · ${s.detail}`);
      if (s.followup) lines.push(`→ ${s.followup}`);
      lines.push('');
    }
  }
  lines.push('## Caveats');
  for (const c of b.caveats) lines.push(`- ${c}`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RC Operator Signals](https://github.com/outsourc-e/rc-operator-signals) — Built by Aurora 🤖*');
  return lines.join('\n');
}

function buildSlack(b: Brief): string {
  const lines: string[] = [];
  lines.push(`*Operator Signals — ${b.project_name}*`);
  lines.push(`_${b.period.start} → ${b.period.end} (last 28 days)_`);
  lines.push('');
  lines.push(`*Snapshot:* MRR ${fmt(b.snapshot.find(m=>m.id==='mrr')?.value??0,'$')} · Active Subs ${(b.snapshot.find(m=>m.id==='active_subscriptions')?.value??0).toLocaleString()} · Trials ${b.snapshot.find(m=>m.id==='active_trials')?.value??0}`);
  lines.push('');
  lines.push('*Signals:*');
  const all = [...b.signals, ...b.contradictions, ...b.watchlist];
  const unique = [...new Map(all.map(s => [s.id, s])).values()];
  for (const s of unique.slice(0, 5)) {
    const icon = s.severity === 'critical' ? '🚨' : s.severity === 'warning' ? '⚠️' : s.severity === 'positive' ? '✅' : '💡';
    lines.push(`${icon} ${s.title}`);
  }
  return lines.join('\n');
}

const SeverityIcon: Record<Severity, string> = {
  info: '💡',
  warning: '⚠️',
  critical: '🚨',
  positive: '✅',
};

export function App() {
  const [copied, setCopied] = useState<string | null>(null);

  const allSignals = [...brief.signals, ...brief.contradictions];
  const uniqueSignals = [...new Map(allSignals.map(s => [s.id, s])).values()];
  const watchlistUnique = [...new Map(brief.watchlist.map(s => [s.id, s])).values()];

  const copyToClipboard = async (text: string, label: string) => {
    await navigator.clipboard.writeText(text);
    setCopied(label);
    setTimeout(() => setCopied(null), 2000);
  };

  const downloadMarkdown = () => {
    const md = buildMarkdown(brief);
    const blob = new Blob([md], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `operator-signals-${brief.project_name.toLowerCase().replace(/\s/g, '-')}-${brief.period.end}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <header className="header">
        <div className="header-inner">
          <a href="/" className="logo">
            <span className="logo-mark">⚡</span>
            <span>RC Operator Signals</span>
          </a>
          <nav className="nav-links">
            <a href="https://github.com/outsourc-e/rc-operator-signals">GitHub</a>
            <a href="/blog">Blog</a>
            <a href="/spec">Spec</a>
            <span style={{ color: 'var(--text-faint)' }}>·</span>
            <span>Built by Aurora 🤖</span>
          </nav>
        </div>
      </header>

      <main>
        <section className="hero">
          <div className="eyebrow">Built on RevenueCat Charts API</div>
          <h1>
            Dashboards show what moved.<br />
            <span className="accent">We show what deserves attention.</span>
          </h1>
          <p>
            An opinionated signal engine that reads your RevenueCat Charts API and tells you
            which moves matter — contradictions, leading indicators, and caveats — separating
            facts from hypotheses.
          </p>
          <a href="#brief" className="cta">
            See the live demo on Dark Noise →
          </a>
          <div className="cta-tagline">No login. No install. Just signals.</div>
        </section>

        <div className="container">
          <div id="brief" className="brief-surface">
            <div className="brief-header">
              <div>
                <div className="brief-header-title">{brief.project_name} — Operator Brief</div>
                <div className="brief-header-meta">
                  <span>{brief.period.start} → {brief.period.end} · 28 days</span>
                  <span className="live-pill">
                    <span className="live-dot"></span> live demo data
                  </span>
                </div>
              </div>
            </div>

            <div className="snapshot">
              {brief.snapshot.map(m => (
                <div key={m.id} className="snapshot-cell">
                  <div className="snapshot-label">{m.name.replace('Number of transactions in the last 28 days', 'Txns 28d')}</div>
                  <div className="snapshot-value">{fmt(m.value, m.unit)}</div>
                  <div className="snapshot-period">{shortPeriod(m.period)}</div>
                </div>
              ))}
            </div>

            <div className="brief-body">
              <section>
                <div className="section-header">
                  <h2>💡 Signals</h2>
                  <span className="subtitle">{uniqueSignals.length} insights</span>
                </div>
                {uniqueSignals.map(s => (
                  <div key={s.id} className="signal-card">
                    <div className="signal-meta">
                      <span className={`severity-pill ${s.severity}`}>
                        {SeverityIcon[s.severity]} {s.severity}
                      </span>
                      <span className="timestamp">just now</span>
                    </div>
                    <div className="signal-title">{s.title}</div>
                    <div className="signal-detail">{s.detail}</div>
                    {s.evidence.length > 0 && (
                      <div className="signal-evidence">
                        <strong>Evidence: </strong>
                        {s.evidence.map((e, i) => (
                          <span key={i} className="evidence-chip">
                            {e.metric}: {e.value.toLocaleString()}
                            {e.period ? ` (${e.period})` : ''}
                          </span>
                        ))}
                      </div>
                    )}
                    {s.followup && (
                      <div className="signal-followup">→ Follow up: {s.followup}</div>
                    )}
                  </div>
                ))}
              </section>

              <section>
                <div className="section-header">
                  <h2>👀 Watchlist</h2>
                  <span className="subtitle">{watchlistUnique.length} to monitor</span>
                </div>
                {watchlistUnique.length > 0 ? watchlistUnique.map(s => (
                  <div key={s.id} className="watchlist-card">
                    <div className="watchlist-row">
                      <div className={`watchlist-dot ${s.severity}`}></div>
                      <div className="watchlist-content">
                        <div className="watchlist-title">{s.title}</div>
                        <div className="watchlist-detail">{s.detail}</div>
                      </div>
                    </div>
                  </div>
                )) : (
                  <div className="watchlist-card">
                    <div className="watchlist-detail" style={{color: 'var(--text-faint)'}}>
                      Nothing on the watchlist right now.
                    </div>
                  </div>
                )}
              </section>
            </div>

            <div className="caveats">
              <div className="caveats-title">ℹ️ Caveats from RevenueCat's chart definitions:</div>
              <ul>
                {brief.caveats.map((c, i) => <li key={i}>{c}</li>)}
              </ul>
            </div>

            <div className="export-row">
              <button className="btn" onClick={() => copyToClipboard(buildMarkdown(brief), 'markdown')}>
                📋 {copied === 'markdown' ? 'Copied!' : 'Copy as Markdown'}
              </button>
              <button className="btn btn-primary" onClick={downloadMarkdown}>
                📥 Download brief.md
              </button>
              <button className="btn" onClick={() => copyToClipboard(buildSlack(brief), 'slack')}>
                🔗 {copied === 'slack' ? 'Copied!' : 'Slack-ready format'}
              </button>
            </div>
          </div>
        </div>
      </main>

      <footer className="footer">
        <div className="footer-content">
          Built by <strong>Aurora 🤖</strong> — autonomous AI agent · Operated by{' '}
          <a href="https://github.com/outsourc-e">@outsourc-e</a> · Built in 48 hours · MIT licensed
          <div className="footer-links">
            <a href="https://github.com/outsourc-e/rc-operator-signals">GitHub</a>
            <a href="https://github.com/outsourc-e/rc-operator-signals/blob/main/PROGRESS.md">Process Log</a>
            <a href="/blog">Blog post</a>
            <a href="https://www.revenuecat.com/docs/api-v2">RevenueCat Charts API docs</a>
          </div>
        </div>
      </footer>
    </>
  );
}
