// CLI entry — `npx rc-operator-signals --demo` or with --key
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { RevenueCatClient } from './api/client.js';
import { buildBrief, type ChartCache } from './engine/rules.js';
import type { Signal, ChartResponse } from './types/index.js';

const __dirname = dirname(fileURLToPath(import.meta.url));

const SEVERITY_ICON: Record<Signal['severity'], string> = {
  critical: '🚨',
  warning: '⚠️ ',
  info: '💡',
  positive: '✅',
};

interface Args {
  demo: boolean;
  key?: string;
  json: boolean;
  markdown: boolean;
  projectId?: string;
}

function parseArgs(argv: string[]): Args {
  const out: Args = { demo: false, json: false, markdown: false };
  for (let i = 2; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--demo') out.demo = true;
    else if (a === '--json') out.json = true;
    else if (a === '--markdown' || a === '--md') out.markdown = true;
    else if (a === '--key' && argv[i + 1]) out.key = argv[++i];
    else if (a === '--project' && argv[i + 1]) out.projectId = argv[++i];
  }
  return out;
}

function fmt(value: number, unit: string): string {
  if (unit === '$') return `$${value.toLocaleString()}`;
  if (unit === '%') return `${value.toFixed(1)}%`;
  return value.toLocaleString();
}

function loadFixture(name: string): unknown {
  const p = join(__dirname, 'fixtures', 'dark-noise', name);
  return JSON.parse(readFileSync(p, 'utf-8'));
}

function printMarkdown(brief: ReturnType<typeof buildBrief>): void {
  const lines: string[] = [];
  lines.push(`# Operator Signals — ${brief.project_name}`);
  lines.push(`> ${brief.period.start} → ${brief.period.end} (last 28 days)`);
  lines.push(`> Generated: ${brief.generated_at}`);
  lines.push('');

  lines.push('## Snapshot');
  lines.push('| Metric | Value |');
  lines.push('|---|---|');
  for (const m of brief.snapshot) {
    lines.push(`| ${m.name} | ${fmt(m.value, m.unit)} |`);
  }
  lines.push('');

  if (brief.signals.length > 0) {
    lines.push('## Signals');
    for (const s of brief.signals) {
      const icon = SEVERITY_ICON[s.severity];
      lines.push(`### ${icon} ${s.title}`);
      lines.push(`**Severity:** ${s.severity.toUpperCase()} · **Type:** ${s.kind}`);
      lines.push('');
      lines.push(s.detail);
      if (s.evidence.length > 0) {
        lines.push('');
        lines.push('**Evidence:** ' + s.evidence.map(e => `${e.metric}: ${e.value}${e.period ? ` (${e.period})` : ''}`).join(' · '));
      }
      if (s.followup) lines.push(`\n→ *${s.followup}*`);
      lines.push('');
    }
  }

  if (brief.watchlist.length > 0) {
    lines.push('## Watchlist');
    for (const s of brief.watchlist) {
      lines.push(`- ${SEVERITY_ICON[s.severity]} **${s.title}** — ${s.detail}`);
    }
    lines.push('');
  }

  lines.push('## Caveats');
  for (const c of brief.caveats) lines.push(`- ${c}`);
  lines.push('');
  lines.push('---');
  lines.push('*Generated by [RC Operator Signals](https://github.com/outsourc-e/rc-operator-signals) · Built by Aurora 🤖*');

  console.log(lines.join('\n'));
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv);

  let projectName = 'Unknown';
  let cache: ChartCache;

  if (args.demo) {
    // Load from fixtures — no API call needed
    const overview = loadFixture('overview.json') as { metrics: ChartCache['overview'] };
    const charts: Record<string, ChartResponse> = {};

    const chartFiles: Array<[string, string]> = [
      ['revenue', 'revenue.json'],
      ['mrr', 'mrr.json'],
      ['actives', 'actives.json'],
      ['actives_movement', 'actives_movement.json'],
      ['trials_movement', 'trials_movement.json'],
      ['churn', 'churn.json'],
    ];

    for (const [key, file] of chartFiles) {
      try {
        charts[key] = loadFixture(file) as ChartResponse;
      } catch {
        // Skip missing fixtures
      }
    }

    cache = { overview: overview.metrics, charts };
    projectName = 'Dark Noise';
  } else {
    // Live API mode
    const apiKey = args.key ?? process.env.REVENUECAT_API_KEY;
    if (!apiKey) {
      console.error('Missing API key. Use --demo, --key sk_..., or set REVENUECAT_API_KEY.');
      process.exit(1);
    }

    const client = new RevenueCatClient({ apiKey });
    let projectId = args.projectId;
    if (!projectId) {
      const projects = await client.listProjects();
      if (projects.items.length === 0) {
        console.error('No projects found.');
        process.exit(1);
      }
      projectId = projects.items[0].id;
      projectName = projects.items[0].name;
    }

    const overview = await client.getOverview(projectId);

    // Fetch key charts (rate limited — 5/min, ~13s between calls)
    const charts: Record<string, ChartResponse> = {};
    for (const slug of ['revenue', 'mrr', 'actives', 'actives_movement', 'trials_movement', 'churn']) {
      try {
        charts[slug] = await client.getChart(projectId, slug, { resolution: 'day' });
      } catch (e) {
        console.error(`Warning: could not fetch chart "${slug}": ${e instanceof Error ? e.message : e}`);
      }
    }

    cache = { overview: overview.metrics, charts };
  }

  const now = new Date();
  const start = new Date(now.getTime() - 28 * 24 * 60 * 60 * 1000);
  const brief = buildBrief(cache, {
    project_name: projectName,
    period: {
      start: start.toISOString().slice(0, 10),
      end: now.toISOString().slice(0, 10),
    },
  });

  if (args.json) {
    console.log(JSON.stringify(brief, null, 2));
    return;
  }

  if (args.markdown) {
    printMarkdown(brief);
    return;
  }

  // Pretty print (terminal)
  console.log('');
  console.log(`📊 RevenueCat Operator Signals — ${brief.project_name}`);
  console.log(`   ${brief.period.start} → ${brief.period.end} (last 28 days)`);
  console.log('');

  console.log('SNAPSHOT');
  for (const m of brief.snapshot) {
    console.log(`  ${m.name.padEnd(40)} ${fmt(m.value, m.unit).padStart(12)}`);
  }
  console.log('');

  const allSignals = [...brief.signals, ...brief.contradictions, ...brief.watchlist];
  const unique = [...new Map(allSignals.map(s => [s.id, s])).values()];

  if (unique.length > 0) {
    console.log('SIGNALS');
    for (const s of unique) {
      console.log(`  ${SEVERITY_ICON[s.severity]} [${s.severity.toUpperCase()}] ${s.title}`);
      console.log(`     ${s.detail}`);
      if (s.followup) console.log(`     → ${s.followup}`);
      console.log('');
    }
  }

  console.log('CAVEATS');
  for (const c of brief.caveats) console.log(`  • ${c}`);
  console.log('');
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
